/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OurWorksRouteImport } from './routes/our-works'
import { Route as ServicesRouteRouteImport } from './routes/services/route'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesDisabilityCareSupportChar38RehabilitationRouteImport } from './routes/services/disability-care-support-&-rehabilitation'
import { Route as ServicesDisasterChar38EmergencyReliefRouteImport } from './routes/services/disaster-&-emergency-relief'
import { Route as ServicesEducationChar38SkillsDevelopmentRouteImport } from './routes/services/education-&-skills-development'
import { Route as ServicesHealthMedicalSupportRouteImport } from './routes/services/health-medical-support'
import { Route as ServicesHumanitarianSupportChar38PovertyAlleviationRouteImport } from './routes/services/humanitarian-support-&-poverty-alleviation'
import { Route as ServicesWashProgramChar38ClimateChangeAwarenessRouteImport } from './routes/services/wash-program-&-climate-change-awareness'
import { Route as ServicesYouthEmpowermentChar38CommunityDevelopmentRouteImport } from './routes/services/youth-empowerment-&-Community-development'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorksRoute = OurWorksRouteImport.update({
  id: '/our-works',
  path: '/our-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRouteRoute = ServicesRouteRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const ServicesDisabilityCareSupportChar38RehabilitationRoute =
  ServicesDisabilityCareSupportChar38RehabilitationRouteImport.update({
    id: '/disability-care-support-&-rehabilitation',
    path: '/disability-care-support-&-rehabilitation',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesDisasterChar38EmergencyReliefRoute =
  ServicesDisasterChar38EmergencyReliefRouteImport.update({
    id: '/disaster-&-emergency-relief',
    path: '/disaster-&-emergency-relief',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesEducationChar38SkillsDevelopmentRoute =
  ServicesEducationChar38SkillsDevelopmentRouteImport.update({
    id: '/education-&-skills-development',
    path: '/education-&-skills-development',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesHealthMedicalSupportRoute =
  ServicesHealthMedicalSupportRouteImport.update({
    id: '/health-medical-support',
    path: '/health-medical-support',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesHumanitarianSupportChar38PovertyAlleviationRoute =
  ServicesHumanitarianSupportChar38PovertyAlleviationRouteImport.update({
    id: '/humanitarian-support-&-poverty-alleviation',
    path: '/humanitarian-support-&-poverty-alleviation',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesWashProgramChar38ClimateChangeAwarenessRoute =
  ServicesWashProgramChar38ClimateChangeAwarenessRouteImport.update({
    id: '/wash-program-&-climate-change-awareness',
    path: '/wash-program-&-climate-change-awareness',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesYouthEmpowermentChar38CommunityDevelopmentRoute =
  ServicesYouthEmpowermentChar38CommunityDevelopmentRouteImport.update({
    id: '/youth-empowerment-&-Community-development',
    path: '/youth-empowerment-&-Community-development',
    getParentRoute: () => ServicesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services': typeof ServicesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/our-works': typeof OurWorksRoute
  '/api/contact': typeof ApiContactRoute
  '/services/disability-care-support-&-rehabilitation': typeof ServicesDisabilityCareSupportChar38RehabilitationRoute
  '/services/disaster-&-emergency-relief': typeof ServicesDisasterChar38EmergencyReliefRoute
  '/services/education-&-skills-development': typeof ServicesEducationChar38SkillsDevelopmentRoute
  '/services/health-medical-support': typeof ServicesHealthMedicalSupportRoute
  '/services/humanitarian-support-&-poverty-alleviation': typeof ServicesHumanitarianSupportChar38PovertyAlleviationRoute
  '/services/wash-program-&-climate-change-awareness': typeof ServicesWashProgramChar38ClimateChangeAwarenessRoute
  '/services/youth-empowerment-&-Community-development': typeof ServicesYouthEmpowermentChar38CommunityDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/our-works': typeof OurWorksRoute
  '/api/contact': typeof ApiContactRoute
  '/services/disability-care-support-&-rehabilitation': typeof ServicesDisabilityCareSupportChar38RehabilitationRoute
  '/services/disaster-&-emergency-relief': typeof ServicesDisasterChar38EmergencyReliefRoute
  '/services/education-&-skills-development': typeof ServicesEducationChar38SkillsDevelopmentRoute
  '/services/health-medical-support': typeof ServicesHealthMedicalSupportRoute
  '/services/humanitarian-support-&-poverty-alleviation': typeof ServicesHumanitarianSupportChar38PovertyAlleviationRoute
  '/services/wash-program-&-climate-change-awareness': typeof ServicesWashProgramChar38ClimateChangeAwarenessRoute
  '/services/youth-empowerment-&-Community-development': typeof ServicesYouthEmpowermentChar38CommunityDevelopmentRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services': typeof ServicesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/our-works': typeof OurWorksRoute
  '/api/contact': typeof ApiContactRoute
  '/services/disability-care-support-&-rehabilitation': typeof ServicesDisabilityCareSupportChar38RehabilitationRoute
  '/services/disaster-&-emergency-relief': typeof ServicesDisasterChar38EmergencyReliefRoute
  '/services/education-&-skills-development': typeof ServicesEducationChar38SkillsDevelopmentRoute
  '/services/health-medical-support': typeof ServicesHealthMedicalSupportRoute
  '/services/humanitarian-support-&-poverty-alleviation': typeof ServicesHumanitarianSupportChar38PovertyAlleviationRoute
  '/services/wash-program-&-climate-change-awareness': typeof ServicesWashProgramChar38ClimateChangeAwarenessRoute
  '/services/youth-empowerment-&-Community-development': typeof ServicesYouthEmpowermentChar38CommunityDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services'
    | '/about'
    | '/blog'
    | '/contact'
    | '/our-works'
    | '/api/contact'
    | '/services/disability-care-support-&-rehabilitation'
    | '/services/disaster-&-emergency-relief'
    | '/services/education-&-skills-development'
    | '/services/health-medical-support'
    | '/services/humanitarian-support-&-poverty-alleviation'
    | '/services/wash-program-&-climate-change-awareness'
    | '/services/youth-empowerment-&-Community-development'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/our-works'
    | '/api/contact'
    | '/services/disability-care-support-&-rehabilitation'
    | '/services/disaster-&-emergency-relief'
    | '/services/education-&-skills-development'
    | '/services/health-medical-support'
    | '/services/humanitarian-support-&-poverty-alleviation'
    | '/services/wash-program-&-climate-change-awareness'
    | '/services/youth-empowerment-&-Community-development'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/services'
    | '/about'
    | '/blog'
    | '/contact'
    | '/our-works'
    | '/api/contact'
    | '/services/disability-care-support-&-rehabilitation'
    | '/services/disaster-&-emergency-relief'
    | '/services/education-&-skills-development'
    | '/services/health-medical-support'
    | '/services/humanitarian-support-&-poverty-alleviation'
    | '/services/wash-program-&-climate-change-awareness'
    | '/services/youth-empowerment-&-Community-development'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesRouteRoute: typeof ServicesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  OurWorksRoute: typeof OurWorksRoute
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-works': {
      id: '/our-works'
      path: '/our-works'
      fullPath: '/our-works'
      preLoaderRoute: typeof OurWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/disability-care-support-&-rehabilitation': {
      id: '/services/disability-care-support-&-rehabilitation'
      path: '/disability-care-support-&-rehabilitation'
      fullPath: '/services/disability-care-support-&-rehabilitation'
      preLoaderRoute: typeof ServicesDisabilityCareSupportChar38RehabilitationRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/disaster-&-emergency-relief': {
      id: '/services/disaster-&-emergency-relief'
      path: '/disaster-&-emergency-relief'
      fullPath: '/services/disaster-&-emergency-relief'
      preLoaderRoute: typeof ServicesDisasterChar38EmergencyReliefRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/education-&-skills-development': {
      id: '/services/education-&-skills-development'
      path: '/education-&-skills-development'
      fullPath: '/services/education-&-skills-development'
      preLoaderRoute: typeof ServicesEducationChar38SkillsDevelopmentRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/health-medical-support': {
      id: '/services/health-medical-support'
      path: '/health-medical-support'
      fullPath: '/services/health-medical-support'
      preLoaderRoute: typeof ServicesHealthMedicalSupportRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/humanitarian-support-&-poverty-alleviation': {
      id: '/services/humanitarian-support-&-poverty-alleviation'
      path: '/humanitarian-support-&-poverty-alleviation'
      fullPath: '/services/humanitarian-support-&-poverty-alleviation'
      preLoaderRoute: typeof ServicesHumanitarianSupportChar38PovertyAlleviationRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/wash-program-&-climate-change-awareness': {
      id: '/services/wash-program-&-climate-change-awareness'
      path: '/wash-program-&-climate-change-awareness'
      fullPath: '/services/wash-program-&-climate-change-awareness'
      preLoaderRoute: typeof ServicesWashProgramChar38ClimateChangeAwarenessRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/youth-empowerment-&-Community-development': {
      id: '/services/youth-empowerment-&-Community-development'
      path: '/youth-empowerment-&-Community-development'
      fullPath: '/services/youth-empowerment-&-Community-development'
      preLoaderRoute: typeof ServicesYouthEmpowermentChar38CommunityDevelopmentRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
  }
}

interface ServicesRouteRouteChildren {
  ServicesDisabilityCareSupportChar38RehabilitationRoute: typeof ServicesDisabilityCareSupportChar38RehabilitationRoute
  ServicesDisasterChar38EmergencyReliefRoute: typeof ServicesDisasterChar38EmergencyReliefRoute
  ServicesEducationChar38SkillsDevelopmentRoute: typeof ServicesEducationChar38SkillsDevelopmentRoute
  ServicesHealthMedicalSupportRoute: typeof ServicesHealthMedicalSupportRoute
  ServicesHumanitarianSupportChar38PovertyAlleviationRoute: typeof ServicesHumanitarianSupportChar38PovertyAlleviationRoute
  ServicesWashProgramChar38ClimateChangeAwarenessRoute: typeof ServicesWashProgramChar38ClimateChangeAwarenessRoute
  ServicesYouthEmpowermentChar38CommunityDevelopmentRoute: typeof ServicesYouthEmpowermentChar38CommunityDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteRouteChildren: ServicesRouteRouteChildren = {
  ServicesDisabilityCareSupportChar38RehabilitationRoute:
    ServicesDisabilityCareSupportChar38RehabilitationRoute,
  ServicesDisasterChar38EmergencyReliefRoute:
    ServicesDisasterChar38EmergencyReliefRoute,
  ServicesEducationChar38SkillsDevelopmentRoute:
    ServicesEducationChar38SkillsDevelopmentRoute,
  ServicesHealthMedicalSupportRoute: ServicesHealthMedicalSupportRoute,
  ServicesHumanitarianSupportChar38PovertyAlleviationRoute:
    ServicesHumanitarianSupportChar38PovertyAlleviationRoute,
  ServicesWashProgramChar38ClimateChangeAwarenessRoute:
    ServicesWashProgramChar38ClimateChangeAwarenessRoute,
  ServicesYouthEmpowermentChar38CommunityDevelopmentRoute:
    ServicesYouthEmpowermentChar38CommunityDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteRouteWithChildren = ServicesRouteRoute._addFileChildren(
  ServicesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesRouteRoute: ServicesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  OurWorksRoute: OurWorksRoute,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
